[2024-06-16 02:03:52 -0300] [26070] [INFO] Starting gunicorn 22.0.0
[2024-06-16 02:03:52 -0300] [26070] [ERROR] Connection in use: ('::', 8793)
[2024-06-16 02:03:52 -0300] [26070] [ERROR] Retrying in 1 second.
[2024-06-16 02:03:53 -0300] [26070] [ERROR] Connection in use: ('::', 8793)
[2024-06-16 02:03:53 -0300] [26070] [ERROR] Retrying in 1 second.
[2024-06-16 02:03:54 -0300] [26070] [ERROR] Connection in use: ('::', 8793)
[2024-06-16 02:03:54 -0300] [26070] [ERROR] Retrying in 1 second.
[2024-06-16 02:03:55 -0300] [26070] [ERROR] Connection in use: ('::', 8793)
[2024-06-16 02:03:55 -0300] [26070] [ERROR] Retrying in 1 second.
[2024-06-16 02:03:56 -0300] [26070] [ERROR] Connection in use: ('::', 8793)
[2024-06-16 02:03:56 -0300] [26070] [ERROR] Retrying in 1 second.
[2024-06-16 02:03:57 -0300] [26070] [ERROR] Can't connect to ('::', 8793)
Traceback (most recent call last):
  File "/home/maira/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/__main__.py", line 58, in main
    args.func(args)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 434, in task_run
    settings.reconfigure_orm(disable_connection_pool=True)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 378, in reconfigure_orm
    configure_orm(disable_connection_pool=disable_connection_pool, pool_class=pool_class)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 251, in configure_orm
    engine_args = prepare_engine_args(disable_connection_pool, pool_class)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 352, in prepare_engine_args
    if is_sqlalchemy_v1():
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/sqlalchemy.py", line 554, in is_sqlalchemy_v1
    return version.parse(metadata.version("sqlalchemy")).major == 1
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for sqlalchemy
Process DagFileProcessor2717-Process:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 154, in _handle_dag_file_processing
    settings.configure_orm()
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 251, in configure_orm
    engine_args = prepare_engine_args(disable_connection_pool, pool_class)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 352, in prepare_engine_args
    if is_sqlalchemy_v1():
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/sqlalchemy.py", line 554, in is_sqlalchemy_v1
    return version.parse(metadata.version("sqlalchemy")).major == 1
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for sqlalchemy
Process DagFileProcessor2718-Process:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 154, in _handle_dag_file_processing
    settings.configure_orm()
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 251, in configure_orm
    engine_args = prepare_engine_args(disable_connection_pool, pool_class)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 352, in prepare_engine_args
    if is_sqlalchemy_v1():
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/sqlalchemy.py", line 554, in is_sqlalchemy_v1
    return version.parse(metadata.version("sqlalchemy")).major == 1
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for sqlalchemy
Process DagFileProcessor2719-Process:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 154, in _handle_dag_file_processing
    settings.configure_orm()
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 251, in configure_orm
    engine_args = prepare_engine_args(disable_connection_pool, pool_class)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 352, in prepare_engine_args
    if is_sqlalchemy_v1():
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/sqlalchemy.py", line 554, in is_sqlalchemy_v1
    return version.parse(metadata.version("sqlalchemy")).major == 1
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for sqlalchemy
Process DagFileProcessor2720-Process:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 154, in _handle_dag_file_processing
    settings.configure_orm()
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 251, in configure_orm
    engine_args = prepare_engine_args(disable_connection_pool, pool_class)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 352, in prepare_engine_args
    if is_sqlalchemy_v1():
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/sqlalchemy.py", line 554, in is_sqlalchemy_v1
    return version.parse(metadata.version("sqlalchemy")).major == 1
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for sqlalchemy
Process DagFileProcessor2721-Process:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 154, in _handle_dag_file_processing
    settings.configure_orm()
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 251, in configure_orm
    engine_args = prepare_engine_args(disable_connection_pool, pool_class)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 352, in prepare_engine_args
    if is_sqlalchemy_v1():
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/sqlalchemy.py", line 554, in is_sqlalchemy_v1
    return version.parse(metadata.version("sqlalchemy")).major == 1
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for sqlalchemy
Process DagFileProcessor2722-Process:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 154, in _handle_dag_file_processing
    settings.configure_orm()
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 251, in configure_orm
    engine_args = prepare_engine_args(disable_connection_pool, pool_class)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/settings.py", line 352, in prepare_engine_args
    if is_sqlalchemy_v1():
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/sqlalchemy.py", line 554, in is_sqlalchemy_v1
    return version.parse(metadata.version("sqlalchemy")).major == 1
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for sqlalchemy
Traceback (most recent call last):
  File "/home/maira/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/__main__.py", line 58, in main
    args.func(args)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 48, in command
    func = import_string(import_path)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 42, in <module>
    from airflow.jobs.local_task_job_runner import LocalTaskJobRunner
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 29, in <module>
    from airflow.models.taskinstance import TaskReturnCode
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1249, in <module>
    class TaskInstance(Base, LoggingMixin):
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 196, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 560, in __init__
    self._scan_attributes()
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1003, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1274, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2383, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "TaskInstance.dag_model" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
Traceback (most recent call last):
  File "/home/maira/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/__main__.py", line 58, in main
    args.func(args)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 48, in command
    func = import_string(import_path)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 42, in <module>
    from airflow.jobs.local_task_job_runner import LocalTaskJobRunner
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 29, in <module>
    from airflow.models.taskinstance import TaskReturnCode
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1249, in <module>
    class TaskInstance(Base, LoggingMixin):
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 196, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 560, in __init__
    self._scan_attributes()
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1003, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1274, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2383, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "TaskInstance.dag_model" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
Traceback (most recent call last):
  File "/home/maira/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/__main__.py", line 58, in main
    args.func(args)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 48, in command
    func = import_string(import_path)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 42, in <module>
    from airflow.jobs.local_task_job_runner import LocalTaskJobRunner
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 29, in <module>
    from airflow.models.taskinstance import TaskReturnCode
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1249, in <module>
    class TaskInstance(Base, LoggingMixin):
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 196, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 560, in __init__
    self._scan_attributes()
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1003, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1274, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2383, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "TaskInstance.dag_model" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
Traceback (most recent call last):
  File "/home/maira/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/__main__.py", line 58, in main
    args.func(args)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 48, in command
    func = import_string(import_path)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 42, in <module>
    from airflow.jobs.local_task_job_runner import LocalTaskJobRunner
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 29, in <module>
    from airflow.models.taskinstance import TaskReturnCode
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1249, in <module>
    class TaskInstance(Base, LoggingMixin):
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 196, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 560, in __init__
    self._scan_attributes()
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1003, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1274, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2383, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "TaskInstance.dag_model" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
Traceback (most recent call last):
  File "/home/maira/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/__main__.py", line 58, in main
    args.func(args)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 48, in command
    func = import_string(import_path)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 42, in <module>
    from airflow.jobs.local_task_job_runner import LocalTaskJobRunner
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 29, in <module>
    from airflow.models.taskinstance import TaskReturnCode
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1249, in <module>
    class TaskInstance(Base, LoggingMixin):
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 196, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 560, in __init__
    self._scan_attributes()
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1003, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1274, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2383, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "TaskInstance.dag_model" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
Traceback (most recent call last):
  File "/home/maira/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/__main__.py", line 58, in main
    args.func(args)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 48, in command
    func = import_string(import_path)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 42, in <module>
    from airflow.jobs.local_task_job_runner import LocalTaskJobRunner
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 29, in <module>
    from airflow.models.taskinstance import TaskReturnCode
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1249, in <module>
    class TaskInstance(Base, LoggingMixin):
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 196, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 560, in __init__
    self._scan_attributes()
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1003, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1274, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2383, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "TaskInstance.dag_model" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
Traceback (most recent call last):
  File "/home/maira/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/__main__.py", line 58, in main
    args.func(args)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 48, in command
    func = import_string(import_path)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 42, in <module>
    from airflow.jobs.local_task_job_runner import LocalTaskJobRunner
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 29, in <module>
    from airflow.models.taskinstance import TaskReturnCode
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1249, in <module>
    class TaskInstance(Base, LoggingMixin):
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 196, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 560, in __init__
    self._scan_attributes()
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1003, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1274, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2383, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "TaskInstance.dag_model" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
Traceback (most recent call last):
  File "/home/maira/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/__main__.py", line 58, in main
    args.func(args)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 48, in command
    func = import_string(import_path)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 42, in <module>
    from airflow.jobs.local_task_job_runner import LocalTaskJobRunner
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 29, in <module>
    from airflow.models.taskinstance import TaskReturnCode
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1249, in <module>
    class TaskInstance(Base, LoggingMixin):
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 196, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 560, in __init__
    self._scan_attributes()
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1003, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1274, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2383, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "TaskInstance.dag_model" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
Traceback (most recent call last):
  File "/home/maira/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/__main__.py", line 58, in main
    args.func(args)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 48, in command
    func = import_string(import_path)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 42, in <module>
    from airflow.jobs.local_task_job_runner import LocalTaskJobRunner
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 29, in <module>
    from airflow.models.taskinstance import TaskReturnCode
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1249, in <module>
    class TaskInstance(Base, LoggingMixin):
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 196, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 560, in __init__
    self._scan_attributes()
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1003, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1274, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2383, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "TaskInstance.dag_model" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
Traceback (most recent call last):
  File "/home/maira/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/__main__.py", line 58, in main
    args.func(args)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 420, in task_run
    task = _dag.get_task(task_id=args.task_id)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 2629, in get_task
    raise TaskNotFound(f"Task {task_id} not found")
airflow.exceptions.TaskNotFound: Task load_to_postgres not found
Traceback (most recent call last):
  File "/home/maira/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/__main__.py", line 58, in main
    args.func(args)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 48, in command
    func = import_string(import_path)
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 42, in <module>
    from airflow.jobs.local_task_job_runner import LocalTaskJobRunner
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 29, in <module>
    from airflow.models.taskinstance import TaskReturnCode
  File "/home/maira/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1249, in <module>
    class TaskInstance(Base, LoggingMixin):
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 196, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 560, in __init__
    self._scan_attributes()
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1003, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1274, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/home/maira/.local/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2383, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "TaskInstance.dag_model" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
